services:
  - type: web
    name: streamfly-bot
    runtime: python
    plan: free
    region: frankfurt
    healthCheckPath: /healthz
    buildCommand: |
      npm install && npm run build
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: APP_URL
        sync: false
      - key: TWITCH_CLIENT_ID
        sync: false
      - key: TWITCH_SECRET
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: DONATALERTS_ACCESS_TOKEN
        sync: false
      - key: WEBHOOK_ENABLED
        value: "true"
      - key: REQUIRE_INIT_DATA
        value: "true"
