// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Add logging to debug Supabase URL issue
console.log("Supabase URL from env:", SUPABASE_URL);
console.log("Supabase Publishable Key from env:", SUPABASE_PUBLISHABLE_KEY);

if (!SUPABASE_URL) {
  console.error("VITE_SUPABASE_URL is not defined!");
  // Throw an error to stop the app if URL is missing, making it clear in logs
  throw new Error("supabaseUrl is required.");
}
if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error("VITE_SUPABASE_PUBLISHABLE_KEY is not defined!");
  throw new Error("supabasePublishableKey is required.");
}


// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});